# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
# base = "dark"

# This will always show the rerun button after making changes in the code.
[server]
fileWatcherType = "poll"

headless = false             # Run Streamlit in headless=true mode for production (no browser window, no developers mode, it is faster)
enableCORS = true            # Disable Cross-Origin Resource Sharing for production
enableXsrfProtection = true  # Disable XSRF protection (if trusted environment)

# Opt-out for user data collection. GDPR policy in Europe.
[browser]
gatherUsageStats = false

[client]
showErrorDetails = "full" # none
toolbarMode = "viewer"

# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# - "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer"    : Hide the developer options. (no deploy button)
# - "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
